checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - tests/*
        - examples/*
        - docs/*

tools:
    external_code_coverage:
        timeout: 600
        runs: 7
